name: "Build package"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
        - uses: actions/checkout@v4
        - run: |
            nix build --json \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push florentinl
