# name: "Build package"
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v4
#         - uses: cachix/install-nix-action@v30
#           with:
#             nix_path: nixpkgs=channel:nixos-unstable
#         - uses: cachix/cachix-action@v15
#           with:
#             name: florentinl
#             authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
#         - run: |
#             nix build --json \
#                 | jq -r '.[].outputs | to_entries[].value' \
#                 | cachix push florentinl
